
################################################################################
#    &&&....&&&    % Project: MSPJ approach for identification of DEGs         #
#  &&&&&&..&&&&&&  % Author: Bo Li, Huachun Yin, Jingxin Tao, Youjin Hao       #
#  &&&&&&&&&&&&&&  % Date: Jun. 1st, 2020                                      #
#   &&&&&&&&&&&&   %                                                           #
#     &&&&&&&&     % Environment: R version 3.5.3;                             #
#       &&&&       % Platform: x86_64-pc-linux-gnu (64-bit)                    #
#        &         %                                                           #
################################################################################

### ****************************************************************************
### code chunk number 06: .
### ****************************************************************************

### Title: A novel meta-analytical approach to improve identification of DEGs. 

# input: eset - a gene expression matrix, genes in lines and samples in columns. 
#        set.n - the number of the subgroups generated by sampling. 
# output: degs - a genelist, including the gene names, pooled SMDs, and so on. 

### ------------------------------------------------------------------------ ###
### Step-01. Loading the gene expression data in *.csv

eset <- get(load("seq.matrix.RData"))
rm(seq.matrix)

### ------------------------------------------------------------------------ ###
### Step-02. Setting the parameters used for re-sampling.

# set.n: the times of resampling, or the number of sub-groups.   
# size.min: the lower limit of sample size in each group.
# size.max: the maximum sample size in each group. 
# ord.gene: which gene you focused on. 

if (!require("coin")) install.packages("coin")

library(coin)


factorial(20)


set.seed(1)
n <- 100
tr <- rbinom(100, 1, 0.5)
y <- 1 + tr + rnorm(n, 0, 3)

diff(by(y, tr, mean))

s <- sample(tr, length(tr), FALSE)
diff(by(y, s, mean))

dist <- replicate(2000, diff(by(sample(y, length(y), FALSE), sample(tr, length(tr), FALSE), mean)))

hist(dist, xlim = c(-3, 3), col = "black", breaks = 100)

abline(v = diff(by(y, tr, mean)), col = "blue", lwd = 2)

sum(dist > diff(by(y, tr, mean)))/2000  # one-tailed test

# for coin package. 

# independence_test(y ~ tr, alternative = "greater")  # one-tailed

independence_test(g10000 ~ sam.lab, data = input)

# independence_test(y ~ tr, alternative = "two.sided")  # two-tailed

# End. 


