
################################################################################
#    &&&....&&&    % Project: MSPJ approach for identification of DEGs         #
#  &&&&&&..&&&&&&  % Author: Bo Li, Huachun Yin, Jingxin Tao, Youjin Hao       #
#  &&&&&&&&&&&&&&  % Date: Jun. 1st, 2020                                      #
#   &&&&&&&&&&&&   %                                                           #
#     &&&&&&&&     % Environment: R version 3.5.3;                             #
#       &&&&       % Platform: x86_64-pc-linux-gnu (64-bit)                    #
#        &         %                                                           #
################################################################################

### ****************************************************************************
### code chunk number 06: Gene selection based on three classic methods.
### ****************************************************************************

# input: eset - a gene expression matrix, genes in lines and samples in columns. 
#        set.n - the number of the subgroups generated by sampling. 
# output: degs - a genelist, including the gene names, pooled SMDs, and so on. 

### ------------------------------------------------------------------------ ###
### Step-01. LIMMA method for RNA-seq data. 

input <- get(load("input.RData"))

### End of Step-01.
### ------------------------------------------------------------------------ ###

### ------------------------------------------------------------------------ ###
### Step-02. edgeR method for RNA-seq data. 

# using coin package. 
# independence_test(y ~ tr, alternative = "greater")  # one-tailed
# independence_test(y ~ tr, alternative = "two.sided")  # two-tailed

library(FSA)

all.genes <- names(input)[-1]

deg.count <- NULL

for (g in all.genes) {
  
  tmp <- Summarize(get(g) ~ sam.lab, data = input, digits = 3)
  
  # print(tmp)
  # boxplot(get(g) ~ sam.lab, data = input)
  
  deg.per <- try(independence_test(get(g) ~ sam.lab, 
                                   data = input), 
                 silent = FALSE)
  
  # deg.Z <- deg.per@statistic@teststatistic
  deg.p <- deg.per@distribution@pvalue(deg.per@statistic@teststatistic)
  
  # This variable, deg.count, stores all the differentially expressed genes.
  
  if (!is.na(deg.p) & deg.p < 0.01) deg.count <- c(deg.count, g) else next
  
}

deg.per <- deg.count; rm(deg.count)

deg.per

# For permutation test of independence
# For two groups as independent samples, and tests if there is a difference in values between the two groups.

# For permutation test of symmetry. 
# For two groups as having paired or repeated data, paired within Individual.

# deg.per <- symmetry_test(g10000 ~ sam.lab | Individual, data = input)

#. class(deg.per)
#. getMethod("show","ScalarIndependenceTest")

### End of Step-02.
### ------------------------------------------------------------------------ ###

### ------------------------------------------------------------------------ ###
### Step-03. DESeq2 method for RNA-seq data. 



### End of Step-03.
### ------------------------------------------------------------------------ ###
